version: '3.9'

services:
  test-app:
    container_name: test-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./:/app/
      - /app/node_modules/
      - /app/apps/server/node_modules/
      - /app/apps/web/node_modules/
      - /app/packages/eslint-config-custom/node_modules/
    depends_on:
      - 'postgres'
    links:
      - 'postgres'
    restart: on-failure

  postgres:
    container_name: test-postgres
    image: postgres:14.4-alpine3.16
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test-db
    ports:
      - 5432:5432
    volumes:
      - './_data/postgres:/var/lib/postgresql/data'

    restart: always

networks:
  test-network:
    driver: bridge

volumes:
  postgres:
